FROM python:3.11-slim

WORKDIR /app

COPY ../frontend-requirements.txt .
RUN pip install --no-cache-dir -r frontend-requirements.txt

COPY ../frontend_1.py .

EXPOSE 8501

CMD ["streamlit", "run", "frontend_1.py", "--server.port=8501", "--server.address=0.0.0.0"]
